"""ParaView helper outputs."""

from __future__ import annotations

from pathlib import Path
from typing import Dict
from xml.sax.saxutils import escape


def _choose_fields_source(output_paths: Dict[str, Dict[str, str]]) -> tuple[str, str] | None:
    xdmf_fields = output_paths.get("xdmf", {}).get("fields")
    if xdmf_fields:
        return "xdmf", xdmf_fields
    vtx_fields = output_paths.get("vtx", {}).get("fields")
    if vtx_fields:
        return "vtx", vtx_fields
    return None


def write_paraview_macro(
    out_dir: str | Path,
    *,
    fields_path: str,
    mesh_path: str | None = None,
) -> str:
    """Write a ParaView Python macro that opens latest results."""
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    macro_path = out_path / "load_latest.py"

    lines = [
        '"""Auto-generated by SimStack."""',
        "",
        "from paraview.simple import OpenDataFile, Render, ResetSession, Show",
        "",
        "ResetSession()",
        f"fields = OpenDataFile(r\"{fields_path}\")",
        "Show(fields)",
    ]
    if mesh_path:
        lines.extend(
            [
                f"mesh = OpenDataFile(r\"{mesh_path}\")",
                "Show(mesh)",
            ]
        )
    lines.append("Render()")
    lines.append("")

    macro_path.write_text("\n".join(lines))
    return str(macro_path)


def write_paraview_template(
    out_root: str | Path,
    output_paths: Dict[str, Dict[str, str]],
    *,
    mesh_path: str | None = None,
    boundary_path: str | None = None,
    tag_map_path: str | None = None,
    provenance_path: str | None = None,
    state_name: str = "latest.pvsm",
) -> Dict[str, str] | None:
    """Write a lightweight ParaView template bundle.

    The `.pvsm` output acts as a path template manifest and is accompanied by
    a `load_latest.py` macro that can be run from ParaView's Python shell.
    """
    chosen = _choose_fields_source(output_paths)
    if chosen is None:
        return None
    fields_format, fields_path = chosen

    paraview_dir = Path(out_root) / "paraview"
    paraview_dir.mkdir(parents=True, exist_ok=True)

    entries = [
        ("fields", fields_path),
    ]
    if mesh_path:
        entries.append(("mesh", mesh_path))
    if boundary_path:
        entries.append(("boundary", boundary_path))
    if tag_map_path:
        entries.append(("tag_map", tag_map_path))
    if provenance_path:
        entries.append(("provenance", provenance_path))

    xml_lines = [
        '<?xml version="1.0"?>',
        "<SimStackParaViewTemplate version=\"1.0\">",
        f"  <Fields format=\"{escape(fields_format)}\" path=\"{escape(fields_path)}\" />",
    ]
    for kind, path in entries[1:]:
        xml_lines.append(f"  <Data kind=\"{escape(kind)}\" path=\"{escape(path)}\" />")
    xml_lines.extend(
        [
            "  <Hint>Run paraview/load_latest.py from ParaView Python shell.</Hint>",
            "</SimStackParaViewTemplate>",
            "",
        ]
    )

    state_path = paraview_dir / state_name
    state_path.write_text("\n".join(xml_lines))

    macro_path = write_paraview_macro(
        paraview_dir,
        fields_path=fields_path,
        mesh_path=mesh_path,
    )

    return {
        "state": str(state_path),
        "macro": str(macro_path),
    }
